---
settings:
  day_offset: 6
  facility: 60a7ac3f-b774-4228-a9a3-056c0a10010d
urls:
  base_url: https://feelgood.wondr.se/
  home: users/start
  logout: users/logout
  schema: schema
  participate: w_booking/activities/participate/
  list: w_booking/activities/list
headers:
  Accept-Encoding: gzip, deflate, br
  Referer: https://feelgood.wondr.se/w_booking/activities
  Sec-Fetch-Dest: empty
  Sec-Fetch-Mode: cors
  Sec-Fetch-Site: same-origin
  accept: application/json
  accept-language: en
  cache-control: no-store
  pragma: no-cache
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: Windows
  x-requested-with: XMLHttpRequest
