name: Book activity - test run

on:
  workflow_dispatch:
    inputs:
      activity:
        type: string
        description: name of the activity
      time:
        type: string
        description: time the activity starts
      day:
        type: string
        description: day of the activity
  repository_dispatch:
    types: [ book_test ]

jobs:
  book:
    runs-on: [self-hosted, KAV]
    steps:
      - uses: actions/checkout@v3
      
      - name: install requirements
        run: python3 -m pip install -r source/requirements.txt
        
      - name: Run booking action test
        run: python3 source/book.py -usr ${{ secrets.FEELGOOD_USER }} -pw ${{ secrets.FEELGOOD_PW }} -tst True --name "${{ inputs.activity }}" --time "${{ inputs.time }}" --day "${{ inputs.day }}"
