name: Lint the code

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci-py${{ matrix.python-version }}
    runs-on: docker-tst
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: python -m pip install .[tests,ci]

      - name: flake8 lint
        run: flake8

      - name: black formatting Check
        run: black --check .
